### ISSUE TITLE
Installer bug

### ISSUE THREAD

**Issue by fblais** [linuxmint/mint21.3-beta#13]
I had LM 21.2 XFCE installed on my HD and decided to wipe it and install from scratch. (I had copied my document elsewhere beforehand)
So when the installer suggested my to replace my 21.2 installation, I chose that option.
It was indicated the documents would be completely deleted.
However it's not what happened.
I use a separate home partition and it was left as is.
Worse, I ended with that partition separately visible in Nemo.

So I started another install but chose the "do something else" option and then configured the root and home partitions manually, as I normally do. (checked to format the home partition)
This time the install was okay.

**Comment by mtwebster** [comment]
You must use the 'do something else' when using a separate home partition.

The replace option would have preserved the home folder while replacing the system, within a single partition (the norm for the default installation).

**Comment by fblais** [comment]
Understood.
But maybe that should be clearly stated under the Replace option text.
