### ISSUE TITLE
Sound did not work after the installation

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/mint21.3-beta#15]
I'm not sure what really caused this, but after installing 21.3 on my computer the sound was not working at all. I was capable of restoring it by manually configuring pipewire and wireplumber as the default sound server though.

I tried to check for tests related to sound in the QA tests at the community page, but I found none, so I decided to create this issue in case there is a problem with the installation.

**Comment by clefebvre** [comment]
Hi @anaximeno,

What pkgs did you install/remove exactly?

**Comment by anaximeno** [comment]
Hi Clem,

I followed this tutorial https://ubuntuhandbook.org/index.php/2022/04/pipewire-replace-pulseaudio-ubuntu-2204/amp/

**Comment by clefebvre** [comment]
I'll close this because I think it's HW related. I definitely have sound in various boxes and VMs here.

**Comment by anaximeno** [comment]
> I'll close this because I think it's HW related. I definitely have sound in various boxes and VMs here.

Yeah, it makes sense, my computer has quite recent hardware so it might be something related to that, I just wanted to confirm it is not a bug specifically with the new version as I had no problems when installing LMDE (which uses pipewire as well).

**Comment by rcalixte** [comment]
> my computer has quite recent hardware

This might be a bad question but have you tried with the 6.2 kernel? LMDE ships with 6.1 and a clean install of Mint 21.3 will default to 5.15 for the kernel.

**Comment by anaximeno** [comment]
> This might be a bad question but have you tried with the 6.2 kernel? LMDE ships with 6.1 and a clean install of Mint 21.3 will default to 5.15 for the kernel.

Yeah, I suspected the kernel could be the reason and installed 6.2, but the sound didn't work still.
