### ISSUE TITLE
xfce: Typo in Thunar uca.xml

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/mint21.3-beta#16]
Check SHA256 doesn't work in Thunar LM21.2. There is a typo in uca.xml.

mint-sha256sum %f is wrong as mint-sha256sum isn't a valid command

replace with sha256sum-mint %f and check sha256 will start to work in Thunar

Ref. https://github.com/orgs/linuxmint/discussions/100
![Screenshot_2023-12-11_09-56-20](https://github.com/linuxmint/mint21.3-beta/assets/47174957/e8837a43-8468-4092-8ea6-85fac2c938fb)

**Comment by MenthaSuaveolens** [comment]
Typo still present in 21.3 Xfce

**Comment by clefebvre** [comment]
Fixed in mint-artwork 1.7.9.

This is obsolete and replaced with mintstick's verify function.

Note: Make sure ~/.config/Thunar is updated or updates itself after the pkg update.
