### ISSUE TITLE
XFCE : Adding Flatpak-applications to the desktop creates a broken link

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/mint21.3-beta#19]
Select a Flatpak-application and add it to the desktop. No desktop-icon is being created.
The screenshot underneath is taken from a desktop where the flatpak-app GoodVibes is being added to the desktop. All Flatpak-applications have this behavior on an XFCE-desktop. On Cinnamon a proper desktop-icon is created.

![Schermafdruk_2023-12-12_13-23-47](https://github.com/linuxmint/mint21.3-beta/assets/47174957/62e093b7-7420-4b90-baf0-b4a2256c73cc)

**Comment by clefebvre** [comment]
Hi @MenthaSuaveolens,

This looks like a specific Xfce issue, either against Thunar or against xfce4-whisker-menu. It should be reported upstream directly.

**Comment by MenthaSuaveolens** [comment]
Hi, apparently some fixes have been made to xfce4-whiskermenu-plugin. Can these be implemented into 21.3? 
https://gitlab.xfce.org/panel-plugins/xfce4-whiskermenu-plugin/-/issues/122#note_82994
