### ISSUE TITLE
PCMemTest No Longer Supported, Use Latest Memtest86+ Instead

### ISSUE THREAD

**Issue by PicoMitchell** [linuxmint/mint21.3-beta#21]
I appreciate effort being put into having a UEFI memtest option, but it looks like you've used the outdated PCMemTest version 1.5 from https://github.com/martinwhitaker/pcmemtest

As stated in that project [README](https://github.com/martinwhitaker/pcmemtest/blob/master/README.md), it is no longer being supported and has merged into Memtest86+ with both of those developers working together now.

The latest version of Memtest86+ is currently 6.20 and supports both Legacy BIOS and UEFI: https://github.com/memtest86plus/memtest86plus

Compiled binaries can be downloaded from https://memtest.org using the "Binary Files" link in the "Downloads" section on the right.

**Comment by SimonIremonger** [comment]
The puzzle / problem is that  ubuntu 22.04 lts is a version where pcmemtest is the latest included.
BUT -- It may actually be sensible to include jammy-backports memtest86+ on the boot image...
https://packages.ubuntu.com/search?keywords=memtest86+
LMDE6 can have normal memtest86+ 6 directly but not sure if it was included in that Debian based release.

**Comment by clefebvre** [comment]
Fixed in upcoming ISOs. Moved to memtest 6.20.
