### ISSUE TITLE
Missing translation in a nemo extension 

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.3-beta#24]
In Nemo-share the description still appears in English, I tried with Spanish and Portuguese.

es.
![es](https://github.com/linuxmint/mint21.3-beta/assets/68134588/ece17a10-5b42-47d7-ab8d-03134dc4f3e1)

pt
![pt](https://github.com/linuxmint/mint21.3-beta/assets/68134588/d073c016-9b25-49e3-aa4d-c01769c23b2e)

**Comment by clefebvre** [comment]
All fixed on master

**Comment by haggen88** [comment]
@clefebvre  The same issue but with another extension  {nemo-emblems}. 


![nemo-emblems](https://github.com/linuxmint/mint21.3-beta/assets/68134588/599d63c3-6854-46ad-ad22-83229cd5fb87)

 the error occurs when updating to nemo-emblems 6.0.1
