### ISSUE TITLE
Sticky issue: Formatting goes away when typing non-ASCII symbols

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint21.3-beta#28]
In german, we have ä, ö, ü and ß, for example. When writing in bold or some other formatted mode and I then type one of these letters, the bold formatting goes away and I have to re-select it manually. See here:

https://github.com/linuxmint/mint21.3-beta/assets/118076740/d952495f-1f5f-4339-b2c3-718bf68ac5de

<sub><sub><sub>this is not a new issue in this beta ;)</sub></sub></sub>

**Comment by clefebvre** [comment]
Confirmed.

**Comment by clefebvre** [comment]
This is caused by this line right here:

https://github.com/linuxmint/sticky/blob/master/usr/lib/sticky/note_buffer.py#L652

When entering a special character, the length value is `2`, not `1`.

**Comment by clefebvre** [comment]
Consequently https://github.com/linuxmint/sticky/blob/master/usr/lib/sticky/note_buffer.py#L687 is not called on special characters and the tag isn't applied going forward.

**Comment by clefebvre** [comment]
Removing the test on the length fixes the issue, but I'm not sure whether it might introduce other problems.
