### ISSUE TITLE
mintinstall - app banners do not display

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.3-beta#3]
![no banner](https://github.com/linuxmint/mint21.3-beta/assets/68134588/3bdc1572-7767-41ec-96ab-8c54a6a6d7fa)

Unlike Mint 21.2 installed on the same computer {screen resolution 1366x768}, the app opens the window in a reduced size and without the banners.
 
mint@mint:~$ mintinstall
MintInstall: low resolution detected (768px height), limiting window height.
MintInstall: Detected system architecture: 'x86_64'
MintInstall: No new reviews
MintInstall: Deleting old screenshots

--
[no banner.tar.gz](https://github.com/linuxmint/mint21.3-beta/files/13601395/no.banner.tar.gz)

**Comment by mtwebster** [comment]
The threshold to limit window size was raised from 768 to 800 to cover more laptop sizes. The window's natural height is around 800, and the banner takes up a lot of space, so in these situations it's hidden to allow more content in the other sections.
