### ISSUE TITLE
Question: does Mint 21.3 Cinnamon fix the panel hiding problems?

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint21.3-beta#30]
The following open issues are filed against Cinnamon about panels not hiding (or unhiding) properly: [this](https://github.com/linuxmint/cinnamon/issues/11803); [this](https://github.com/linuxmint/cinnamon/issues/11087); [this](https://github.com/linuxmint/cinnamon/issues/9251); [this](https://github.com/linuxmint/cinnamon/issues/8570).

I myself have that problem (and specifically the problem I have is with auto-hiding panels sometimes getting stuck, i.e. not hiding). I tried to reproduce that problem on my two Mint laptops under 21.3 beta (Cinnamon flavour). I failed (even when using step 1 in [this one](https://github.com/linuxmint/cinnamon/issues/11087) of the aforementioned issues). Still, the problem - on 21.2 - _is_ intermittent.

Is there reason to believe the problem fixed, please?

**Comment by clefebvre** [comment]
It's possible this fixed it: https://github.com/linuxmint/cinnamon/pull/11788

**Comment by LinuxOnTheDesktop** [comment]
@clefebvre: aha.

I have, perhaps unwisely, just now replaced the relevant `applet.js` file on one of my Mint 21.2 systems with the code [here](https://raw.githubusercontent.com/linuxmint/cinnamon/a80336bebb15033026fc595103c766dce7d8dd0d/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js) (and restarted Cinnamon). I will see whether it fixes the problem.

**Comment by fredcw** [comment]
No, this is a different bug that's still exists. It may have something to do with the system tray but I couldn't see any obvious cause.
