### ISSUE TITLE
Pragmatic interim for Known Bug with /boot filling up

### ISSUE THREAD

**Issue by SimonIremonger** [linuxmint/mint21.3-beta#31]
There is the known, pre-existing issue, that -- for systems with separate /boot -- the package system jams up horribly due to filling up /boot.   This is happening because mintupdate arrangement is doing its' own thing with kernels and not clearing up the old kernel packages, and after a while /boot fills up.  This can be fiddly to resolve with sudo dpkg --configure -a  and so-on!.

I can only express that I have tested the "remove obsolete kernels" automation for years on many machines and never had any trouble.

I would like to propose for 21.3 that, somehow or other (either by change to mintupdate setting itself up -or- change to mint 21.3 installer / scripts), for those with separate /boot  this particular automation is turned on by default.  In this way there will be some wider testing, the most serious issue is resolved, but the exposure to a possible regression is also small.

**Comment by clefebvre** [comment]
I'm not keen on having apt autoremove run automatically without the user knowing about it.

Here's a scenario:

- Install a metapackage
- remove one pkg which removes the meta
- see autoremove remove everything else

Say you install kde-desktop and remove konqueror (or whatever it depends on), this would result in KDE getting removed for everybody, silently, during the week.

This is a big no no.

I'd be more keen on rewriting the mintupdate remove feature so it gets its list of autoremovable packages from APT, but then doesn't rely on apt autoremove to clean up older kernels.

There is configuration in place in APT to preserve from considering one old kernel an autoremovable package. So we can query APT to list autoremovable packages for us.. then parse that list to ONLY remove kernel related packages. We could also double check that these don't correspond to the actively running kernel.

With this in place, then I think it would be safe to have this automation enabled, but not as it is implemented right now.

**Comment by clefebvre** [comment]
Added to roadmap for Mint 22.

**Comment by SimonIremonger** [comment]
@clefebvre 
I thought, mintupdate on ubuntu version of mint already has a remove obsolete kernels tunable already which is NOT as wide ranging as apt autoremove, just kernels managed by mintupdate already -- designed already to:-
Never remove manually installed kernels
Never remove running kernel
Always leave one older kernel.
I was not aware this was "apt autoremove" based by any means -- can you check and elaborate?

**Comment by clefebvre** [comment]
Hi @SimonIremonger, it's basically a call to "apt autoremove", yes.

It's smarter since it relies on timers and dpkg's configuration makes it so the second-last kernel is ignored from the list, but it's basically an apt autoremove call.

Manually installed packages are marked as such, so they evade APT's autoremove detection.
The newest kernel is safe because it's a dependency of the meta package.
The second last kernel is safe because of a fancy configuration mechanism (that's from Ubuntu, possibly Debian as well).
The running kernel... mwell... afaik, that one isn't protected.
