### ISSUE TITLE
Missing support for the ASIX AX88772B USB to Ethernet adapter

### ISSUE THREAD

**Issue by pingvin337** [linuxmint/mint21.3-beta#32]
Missing support for the ASIX AX88772B USB to Ethernet adapter. Consequently, there is no Internet access.

Linux Mint 21.3 beta live DVD on an AMD Athlon II 245e system. Gigabyte GA-78LMT-USB3 mainboard.

Running lsusb in terminal shows that the adapter is present.

Running Mint 21.2 live from DVD on the same hardware, this adapter is supported.

**Comment by rcalixte** [comment]
Are you referring to the Mint 21.2 EDGE ISO? That ships with the 6.2 kernel, specifically for supporting newer devices? Mint 21.3 is not an EDGE release. You can install the 6.2 kernel after it is installed though or install 21.2 and upgrade.

**Comment by pingvin337** [comment]
The Mint 21.2 ISO  that supports this adapter is the default one, not EDGE.

The ASIX AX88772B chip is legacy kit, I would say. Linux has supported it for years. Windows drivers that came with this adapter are from 2010.

**Comment by leigh123linux** [comment]
> The Mint 21.2 ISO that supports this adapter is the default one, not EDGE.
> 
> The ASIX AX88772B chip is legacy kit, I would say. Linux has supported it for years. Windows drivers that came with this adapter are from 2010.

You will need to report your issue against the ubuntu kernel at their bug tracker.

**Comment by clefebvre** [comment]
This sound like a kernel regression.

I'd recommend trying 21.2 EDGE to make sure 6.2 works fine with this device.

We'll also be making a 21.3 EDGE in January with a kernel 6.5.
