### ISSUE TITLE
The virtual keyboard is not completely disabled from the accessibility menu

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.3-beta#33]
The virtual keyboard is reactivated after launching it

steps to follow
1 disable the virtual keyboard from the accessibility menu (disable the option: Enable the on-scren keyboard )
2 open the menu and launch virtual keyboard

**Comment by mtwebster** [comment]
This isn't really an issue - if you want the keyboard you should get the keyboard. The menu entry and the osk applet will enable it if it's not already. I don't think wondering why my start menu entry doesn't do anything would be an improvement here.

It may be more useful to consider the switch in Accessibility settings as only intended for people who use the alternate activation mode, which shows/hides the keyboard automatically when appropriate.
