### ISSUE TITLE
Mintsources 2.2.8 MUST be ported to Victoria!

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint21.3-beta#34]
Or at least the commit... ref: https://github.com/linuxmint/mintsources/commit/4e2418b2529f23866243306a00b33be3774e52ac#commitcomment-135018196

<sub><sub><sub><sub><sub>This has nothing to do with this BETA maybe but it needs attention, doesn't it?! ;)</sub></sub></sub></sub></sub>

**Comment by clefebvre** [comment]
Done.
