### ISSUE TITLE
Show mint security updates as those in mintUpdate

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint21.3-beta#37]
In the mint update manager, updates from the ubuntu/debian security updates repo and all updates of firefox, thunderbird and chromium are labelled as security updates. However, there was a recent security update of xviewer that was marked as software, not security update.

**Comment by clefebvre** [comment]
Indeed, that feature is limited and the type of update depends on its origin. I'll close this for now because it's not a regression here in this BETA, it's something we can think about going forward though.
