### ISSUE TITLE
Battery Issues (since upgrade to v21 from v20)

### ISSUE THREAD

**Issue by serapath** [linuxmint/mint21.3-beta#38]
Lenovo 6th Gen Thinopad X1 Carbon Ultrabook

Linux Mint 21.3 (Xfce) displays "Waiting to discharge" when hovering the battery tray icon.

Charging didnt work at all after the upgrade.
Resetting the BIOS made it work to some degree.

The power indicator LED is now alive again, but it blinks in irregular intervals (5-10 secs. between blinks).
The power on button has a green always on LED aswell, but every time the power indicator LED flickers, the power button LED blinks 3 times.

At least things are now working again and the system boots, but this is still far from ideal.

I can provide further information, but what I do know is that this started appearing after the kernel or rather linux mint major version upgrade

**Comment by mtwebster** [comment]
Have you tried other kernels? I can't see it being anything other than that - nothing in Xfce would affect hardware indicators on your laptop. The installed kernel from the ISO is the 5.15 LTS - perhaps you'd upgraded to a newer line in your previous install?
