### ISSUE TITLE
LDME6: system completely crashes after dozen of hours of screensaver

### ISSUE THREAD

**Issue by lm2lm2** [linuxmint/mint21.3-beta#39]
i think mint/lmde shares the same bugreport (guess it's not just a forum for lmde)

using lmde6 since few days, i noticed that with few activities (vlc, ff, gimp..), after a while of not using the computer, the screensaver comes has normally.
But.
(yes there is a but, if not this bugreport would exist)
But, the problem is that after few dozen of minutes (usually less than half an hour), the computer gets totally frozen, even if the screensaver still show something, eg the hour of the last minute the computer was unfroze

eg at 17:02 you can see the computer with hard drive working huge more than on a common usage, without any different activity than an hour ago.. but the computer is frozen on screensaver at time of 16:22 and goes almost to it's first hour of completely freeze: congratulation !

it's just possible to kill the X server with the magic keys (here the K to kill it, the F cant force the problematic software to close, instead of destroying the whole X) to unfreeze the computer (and loose everything of work) and reboot it with common tty ctrl/alt/del to avoid salvage electric restart... if you see what i mean...

i will try to provide a dmesg or maybe others commands? as when i kill with K magic key i always just reboot directly after it, to avoid loosing more time, after lost of data! ..

thank you

**Comment by anaximeno** [comment]
I believe this is not the best place for this bug because the idea is to test the beta for the new release of mainline 21.3 for bugs. Anyway, can you provide more information about your device? Search in the menu for the 'System info' app, click on the 'Upload system info' button, and send the URL open on your browser.
