### ISSUE TITLE
mintinstall - when uninstalling an app flatpak does not delete the app data

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.3-beta#4]
After uninstalling a flatpak app, things like the cache, application data, and app permissions are still retained.

steps to reproduce

1- install a flatpak app
2- uninstall it
3- check the folder of the app in /.var/app/

I suppose it is possible to remove the cache and this data, which in some cases may be of considerable size,
I mean run: [flatpak uninstall --delete-data](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-uninstall)

**Comment by mtwebster** [comment]
This doesn't seem any different than system packaged apps - if you uninstall them, they still leave their ~/.config files and anything they may have put in ~/.cache, as well as other settings.

I use the Brave flatpak regularly, and I'm happy that if I have to re-install it, or reinstall mint, I don't have to go thru setting it up again.

I guess we might consider a way of allow the user to opt in per-app (a 'remove all data' checkbox next to the uninstall button maybe?).

**Comment by johnandmegh** [comment]
> I guess we might consider a way of allow the user to opt in per-app (a 'remove all data' checkbox next to the uninstall button maybe?).

FWIW Gnome Software handles this by an uninstall-time pop-up prompt to keep or delete data, and KDE Discover handles this by leaving a banner on the app page after uninstall is complete giving the option to then delete the remaining data. Both are pretty recent developments in the respective store apps, so I'm not sure which approach has caused more/fewer issues.

This also doesn't seem like a unique-to-21.3-beta issue?

**Comment by haggen88** [comment]
> I guess we might consider a way of allow the user to opt in per-app (**a 'remove all data' checkbox next to the uninstall button maybe?**).

Could be a good option, before using the terminal to manage flatpak app cleaning I used Flatsweep; but it would be more useful to be able to do a complete uninstall from the Software Manager.

**Comment by clefebvre** [comment]
I'd rather see this in a cleaning utility personally. As Michael said, we've got the very same problem with APT purge.

Such a tool is already on the roadmap.
