### ISSUE TITLE
login screen keyboard layout

### ISSUE THREAD

**Issue by umikali222** [linuxmint/mint21.3-beta#40]
On the login screen (when you turn your pc on) the keyboard layout is the default one, picked while installing the system.

**Comment by zsolaj** [comment]
Of course it is. What else should it be until you change it in the settings?

**Comment by anaximeno** [comment]
@umikali222, if I understood correctly, the behavior you want is for the change on the keyboard layout on the login screen to persist on reboot. Is that correct?

**Comment by umikali222** [comment]
yes.

**Comment by clefebvre** [comment]
The greeter is there to let you log in. It reads the system's configuration but doesn't write it. Before you're logged in, you could be anyone, including someone with no permissions and no account on the computer.

I don't like the idea of random people affecting the system wide configuration.

There's not much to gain either. If you want the same default keyboard layout for all users, as root, just edit /etc/default/keyboard.
