### ISSUE TITLE
mintstick: verify.py uses an unsafe subprocess call.

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint21.3-beta#42]
yeah. That's really bad practice. https://github.com/linuxmint/mintstick/blob/1e49c7f112080e9fb8fc7edf3395725c8ec4cdd4/lib/verify.py#L177 It's just stupid.
Well, it isn't really. It's a quick way to get what you want. But that way is not safe. It's insecure.
So, what does this security issue allow you? It allows you to send an iso file with a funny name to somebody who uses Linux Mint and ask him if he could verify it because you don't have Linux Mint... well, that's it. You can name the file like this: `fake iso image.iso'  || ls && firefox linuxmint.com & echo 'THIS FILE IS A TRUSTED AND VERIFIED IMAGE OF THE TYPE .iso`
You can open or install apps. You can open your own malicious website. You can create another iso file in the same directory and maybe make sha256sum check the signature of the wrong file. You ~can even include~ (no you can't because that would mean you're criminal of the worst kind) some rm statement in it. The only thing you can't is to include some / because these aren't allowed in filenames. So, what can you do?
Here is a video so I don't have to explain everything here. You only need to know where to put these nice ' in your filename to make sure your commands are really executed. Good luck and I hope you'll find a sha256sum python library soon ;)

https://github.com/linuxmint/mint21.3-beta/assets/118076740/4fb952de-91e2-4acc-8bbf-52d612501b0e

**Comment by mtwebster** [comment]
You need to dial it back a bit, there's no reason for that insulting and condescending attitude.

**Comment by carlosmintfan** [comment]
@mtwebster Sorry Mike, I was joking a bit, yes, don't need to take this as an insult ❤️
