### ISSUE TITLE
Workman caps lock backspace

### ISSUE THREAD

**Issue by umikali222** [linuxmint/mint21.3-beta#44]
in the English (Workman) keyboard layout, when you press caps lock, it presses backspace too. I'll try writing somethingWITH CAPS LOCK O. When I pressed caps lock, it deleted the last character.

**Comment by mtwebster** [comment]
From what I can see, caps-lock *is* backspace in the Workman layout. It's the toggling of caps-lock that is incorrect.

https://workmanlayout.org/

This looks like a bug in the 'xkeyboard-config' package, as the bugginess shows also in the sample layout viewer (keyboard icon below the list of layouts if you're using cinnamon).

I'm not sure what desktop you're using, but in Cinnamon, you can go into keyboard layout settings, click 'Options' in the lower right corner, then expand 'Caps Lock behavior'.  I was able to make capslock only perform a backspace (per the layout spec), and move capslock itself to the Escape key (the Swap Esc and Caps Lock option).

If you really need capslock to remain capslock, you may need to look into modifying the keymap (using something like `xmodmap` or creating your own layout. I usually point people here: https://askubuntu.com/questions/482678/how-to-add-a-new-keyboard-layout-custom-keyboard-layout-definition

info on xkeyboard-config, including bug tracker link:
https://www.freedesktop.org/wiki/Software/XKeyboardConfig/Development/
