### ISSUE TITLE
Audio crackling caused by speech-dispatcher on certain hardware with workaround

### ISSUE THREAD

**Issue by brunoooooooooooooo** [linuxmint/mint21.3-beta#46]
speech-dispatcher can be killed as a temporary solution or uninstalled fully as a permanent solution. looking around forums many people have been having issues with it. so far happened only on mint and debian for me. doesn't happen on headphones. only on monitor speakers

**Comment by clefebvre** [comment]
I guess it's a good workaround.

The actual issue would need to be identified and solved. This is upstream from us. Speech-dispatcher comes preinstalled pretty much everywhere, in Mint, Debian, Ubuntu.
