### ISSUE TITLE
Cinnamon 6.0 broke clipboard-qr applet

### ISSUE THREAD

**Issue by Tibladar** [linuxmint/mint21.3-beta#5]
The commit https://github.com/linuxmint/cinnamon/commit/52037a9690c476046c6247a9ffacca84ebcf77b5 broke the applet [Clipboard QR code](https://cinnamon-spices.linuxmint.com/applets/view/213).

See issue for more details: https://github.com/linuxmint/cinnamon-spices-applets/issues/5166

Either the applet needs to be updated or Cinnamon needs a path to ensure backwards compatibility.
Since nothing in this commit indicates any changes that need to be considered by the applet developers, I think it's a bug in Cinnamon.

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/cinnamon/commit/ba15e7eea3670d5053452b6630385d65c6e3217d

**Comment by Tibladar** [comment]
The commit fixes the issue, the applet now works.
Thanks for the quick solution!
