### ISSUE TITLE
Pip warning

### ISSUE THREAD

**Issue by nilslindemann** [linuxmint/mint21.3-beta#50]
Hello devs,

Could someone please update the [devscripts package](https://github.com/orgs/linuxmint/discussions/196#discussion-5776973)?

Alternatively, to what does it belong, and can I uninstall that without danger, and how? (I may have installed this when going through [this](https://linuxmint-developer-guide.readthedocs.io/en/latest/), but not sure).

Greetings, Nils

**Comment by clefebvre** [comment]
Hi @nilslindemann, it's used to build debian packages. If you went through the Dev guide you probably installed it alright.

We don't need/use pip though. I would recommend against using multiple package managers personally unless you need it for personal work. When that is the case you can also use a private env to avoid conflicts.

Regarding the issue, I see it being tracked at https://bugs.launchpad.net/ubuntu/+source/distro-info/+bug/1991606. This is upstream from us and Ubuntu is already aware of it.
