### ISSUE TITLE
Using backspace when cropping etc. an image closes the cropping etc. option but I want to delete numbers from the entries!

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint21.3-beta#51]
Regression in one of the latest releases following pix gThumb rebase.
https://github.com/linuxmint/pix/issues/197
Not new in this beta, but in one of the last releases I think.
Please tell me if you are angry because I'm reporting older bugs in this beta.
Thanks.

**Comment by clefebvre** [comment]
angry? No :)

**Comment by clefebvre** [comment]
Closing as fixed. We'll update the translations before tagging pix.
