### ISSUE TITLE
Pix makes mint logout bug

### ISSUE THREAD

**Issue by mhborazan** [linuxmint/mint21.3-beta#52]
![Ekran Görüntüsü - 2024-01-03 00-19-48](https://github.com/linuxmint/mint21.3-beta/assets/47061833/833ffe4f-aed6-4fd0-8920-9479cc0fbfd7)
I was discovering softwares from the menu. When I clicked Graphics>Pix Mint logged out. I am surpised and tried again and same thing happened. Idk if it is only me. A weird bug.

**Comment by mtwebster** [comment]
Please check the System Reports app, under Crash reports, to see if there are any entries that are pix or cinnamon-related (if it's really causing you to be logged out, i might expect 'cinnamon-session').

**Comment by mhborazan** [comment]
(probably) after restart, I don't get that problem anymore. First time in my life I faced such a weird thing :)

There is not a report about it.

**Comment by mtwebster** [comment]
Great, going to close this then.
