### ISSUE TITLE
WordPress permalinks to be better

### ISSUE THREAD

**Issue by Neustradamus** [linuxmint/mint21.3-beta#55]
Dear @linuxmint team,

Can you improve the Linux Mint WordPress and uses %postname% permalinks instead of a number?
- https://wordpress.org/documentation/article/customize-permalinks/

Thanks in advance.

**Comment by clefebvre** [comment]
Thanks.

I'm closing the report since it's not related to the BETA.

**Comment by Neustradamus** [comment]
@clefebvre: It has been solved?
Do not close an unsolved ticket ;)

Where I can publish the ticket if it is not the good place?
