### ISSUE TITLE
Question: mint-artwork doesn't seem to be available on your github

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint21.3-beta#58]
Is it wanted that the source code of mint-artwork is not available on Github? Could it potentially be made available?

**Comment by mtwebster** [comment]
Make sure source repositories are enabled in mintsources.

```
apt source mint-artwork
```

**Comment by carlosmintfan** [comment]
Yes, but it's still not github, for pull requests for example, and a quick look at commits... :) But not important
