### ISSUE TITLE
l10n: The 'actions' item displayed in the cinnamon menu does not appear correctly translated.

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint21.3-beta#7]
I thought it was a language pack problem, but I checked in Launchpad for spanish and it seems to be ok. 
I installed the portuguese language pack and the same thing happens.

spanish:
![acciones -es](https://github.com/linuxmint/mint21.3-beta/assets/68134588/f6c21c12-8a70-472e-bee2-8317a09f5bb4)

portuguese:
![acciones -pt](https://github.com/linuxmint/mint21.3-beta/assets/68134588/f1afd652-31df-46c7-afe1-4ca84d8fb2b3)

**Comment by rcalixte** [comment]
It looks like the translations just need to get pulled in for the .desktop files [here](https://github.com/linuxmint/cinnamon/tree/master/files/usr/share/applications).

**Comment by clefebvre** [comment]
Fixed in https://github.com/linuxmint/cinnamon/commit/07c8ddefff57022b54647d686cacd8ead2db5873
