### ISSUE TITLE
Missing Icons in Freecad

### ISSUE THREAD

**Issue by pilatomic** [linuxmint/mint21.3-beta#8]
Compared to Mint 21.1, wrongs icons (New / Open / Save / Print) in Freecad (tested using exactly the same version), both fresh installs in VirtualBox.
The behavior is the same with both with the Repository version and the Flatpak version.

![image](https://github.com/linuxmint/mint21.3-beta/assets/6799093/8a95c32d-614b-4569-b40c-678a84a19ee5)

**Comment by clefebvre** [comment]
Fixed in mint-y-icons 1.7.0 and mint-l-icons 1.6.7.

**Comment by pilatomic** [comment]
I can confirm this is fixed
